#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
define('PATH_ROOT', __DIR__);
Sincco\Sfphp\Paths::init();
if(file_exists(PATH_CONFIG . '/config.xml')) {
	unlink(PATH_CONFIG . '/config.xml');
}
$files = glob(PATH_CACHE . '/*'); 
foreach($files as $file){
	if(is_file($file) and ($file != __FILE__)) {
		unlink($file); 
	}
}
$app = new Sincco\Sfphp\Command;

// Información general
echo "----- APP -----".PHP_EOL;
$params = [];
$params[] = 'sfphp';
$params[] = 'app';
$params[] = 'init';
if (PHP_OS == 'WINNT') {
	echo 'Nombre: (Nuevo Sistema) ';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Nombre: (Nuevo Sistema)');
}
$params[] = (trim($input) == '') ? 'Nuevo Sistema' : $input;
if (PHP_OS == 'WINNT') {
	echo 'Compañía: (Mi Cliente) ';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Compañía: (Mi Cliente)');
}
$params[] = (trim($input) == '') ? 'Mi Cliente' : $input;
if (PHP_OS == 'WINNT') {
	echo 'Host: (http://' . str_replace(' ', '', strtolower($params[3])) . '.net/)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Host: (http://' . str_replace(' ', '', strtolower($params[3])) . '.net/)');
}
$params[] = (trim($input) == '') ? 'http://' . str_replace(' ', '', strtolower($params[3])) . '.net/' : $input;
$params[] = 'force';
$app->run($params);
if (PHP_OS == 'WINNT') {
	echo 'Habilitar Cache [Y/N]: (Y)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = strtoupper(readline('Habilitar Cache [Y/N]: (Y)'));
}
$cache = (trim($input) == 'Y' || trim($input) == '') ? 'on' : 'off';
$app->run(['sfphp','cache',$cache]);

// Bases de datos
echo PHP_EOL.PHP_EOL;
echo "----- BASE DE DATOS -----".PHP_EOL;
echo ":: Mysql ::".PHP_EOL;
$params = [];
$params[] = 'sfphp';
$params[] = 'app';
$params[] = 'db';
$params[] = 'default';
$params[] = 'mysql';
if (PHP_OS == 'WINNT') {
	echo 'Host: (localhost)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Host: (localhost)');
}
$params[] = (trim($input) == '') ? 'localhost' : $input;
if (PHP_OS == 'WINNT') {
	echo 'Usuario: (' . str_replace(' ', '', strtolower($params[3])) . ')';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Usuario: (' . str_replace(' ', '', strtolower($params[3])) . ')');
}
$params[] = (trim($input) == '') ? '' . str_replace(' ', '', strtolower($params[3])) : $input;
if (PHP_OS == 'WINNT') {
	echo 'Base: (' . str_replace(' ', '', strtolower($params[3])) . ')';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Base: (' . str_replace(' ', '', strtolower($params[3])) . ')');
}
$params[] = (trim($input) == '') ? '' . str_replace(' ', '', strtolower($params[3])) : $input;
if (PHP_OS == 'WINNT') {
	echo 'Password: (password)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Password: (password)');
}
$params[] = (trim($input) == '') ? 'password' : $input;
$app->run($params);
echo ":: SAE ::".PHP_EOL;
$params = [];
$params[] = 'sfphp';
$params[] = 'app';
$params[] = 'db';
$params[] = 'sae';
$params[] = 'firebird';
if (PHP_OS == 'WINNT') {
	echo 'Host: (C:\SAE\\)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Host: (C:\SAE\)');
}
$params[] = (trim($input) == '') ? 'C:\SAE\\' : $input;
if (PHP_OS == 'WINNT') {
	echo 'Usuario: (SYSDBA)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Usuario: (SYSDBA)');
}
$params[] = (trim($input) == '') ? 'SYSDBA' : $input;
if (PHP_OS == 'WINNT') {
	echo 'Base: (SAE601.FDB)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Base: (SAE601.FDB)');
}
$params[] = (trim($input) == '') ? 'SAE601.FDB' : $input;
if (PHP_OS == 'WINNT') {
	echo 'Password: (masterkey)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = readline('Password: (masterkey)');
}
$params[] = (trim($input) == '') ? 'masterkey' : $input;
$app->run($params);

echo PHP_EOL.PHP_EOL;
echo "----- EXTRAS -----".PHP_EOL;
if (PHP_OS == 'WINNT') {
	echo 'Cargar datos iniciales a la base [Y/N]: (Y)';
	$input = stream_get_line(STDIN, 1024, PHP_EOL);
} else {
	$input = strtoupper(readline('Cargar datos iniciales a la base [Y/N]: (Y)'));
}
if ((trim($input) == 'Y' || trim($input) == '') ? true : false) {
	if (PHP_OS == 'WINNT') {
		echo 'Archivo: (data.sql)';
		$input = stream_get_line(STDIN, 1024, PHP_EOL);
	} else {
		$input = readline('Archivo: (data.sql)');
	}
	$input = (trim($input) == '') ? 'data.sql' : $input;
	$app->run(['sfphp','db','restore','default',$input]);
}
$params = [];
$params[] = 'sfphp';
$params[] = 'app';
$params[] = 'user';
$params[] = 'sincco';
$params[] = 'contacto@sincco.com';
$password = substr(strtoupper(md5(microtime().rand())), 0, 8);
$params[] = $password;
$app->run($params);
echo PHP_EOL.PHP_EOL;
echo "-------------------------------------" . PHP_EOL;
echo "Feliciades! Has instalado el sistema!" . PHP_EOL;
echo "El usuario inicial es sincco::" . $password.PHP_EOL;
echo "-------------------------------------" . PHP_EOL;
echo PHP_EOL.PHP_EOL.PHP_EOL.PHP_EOL;