#!/usr/bin/env php
<?php
# NOTICE OF LICENSE
#
# This source file is subject to the Open Software License (OSL 3.0)
# that is available through the world-wide-web at this URL:
# http://opensource.org/licenses/osl-3.0.php
#
# -----------------------
# @author: Iván Miranda (@deivanmiranda)
# @version: 1.0.0
# -----------------------
# FOR SUPPORTED COMMANDS, SEE REGISTERED FUNCTIONS
# -----------------------

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/paths.php';

use Sincco\Sfphp\Config\Writer;
use \Sincco\Sfphp\Config\Reader;
use \Sincco\Sfphp\Crypt;
use Sincco\Sfphp\DB\DataManager;

main($argv);

/**
 * Main function ( launcher )
 * @param  array $argv Params from command line
 * @return none
 */
function main($argv) {
	array_shift($argv);
	$command = array_shift($argv);
	$action = array_shift($argv);
	$params = $argv;

	if( is_callable( $command . '_' . $action ) )
		call_user_func( $command . '_' . $action, $params );
	else
		echo 'Comando no reconocido' . PHP_EOL;
	die();

	switch ( $command ) {
		case 'db':
			switch ( $params[ 0 ] ) {
				case 'update': dbUpdate(); break;
				case 'backup': dbBackup( $params[ 1 ] ); break;
				default: echo 'Accion no reconocida'.PHP_EOL; break;
			}
			break;
		case 'cache':
			switch ( $params[ 0 ] ) {
				case 'clean': cacheClean(); break;
				default: echo 'Accion no reconocida'.PHP_EOL; break;
			}
			break;
		case 'session':
			switch ( $params[ 0 ] ) {
				case 'clean': sessionClean(); break;
				default: echo 'Accion no reconocida'.PHP_EOL; break;
			}
			break;
		default: echo 'Comando no reconocido'.PHP_EOL; break;
	}
}

function app_init( $data ) {
	echo 'Reiniciando configuración de aplicación...' . PHP_EOL;
	unlink( PATH_CACHE . '/__config.php.cache');
	$_llave_encripcion = strtoupper(md5(microtime().rand()));
	$bases = [];
	$_config = [
		'app' => [
			'key' => $_llave_encripcion,
			'name' => 'salamandra',
			'company' => $data[ 0 ],
			'timezone' => 'America/Chicago',
		],
		'front' => [
			'url' => $data[ 1 ],
		],
		'bases' => $bases,
		'sesion' => [
			'type' => 'DEFAULT',
			'name' => 'salamandra',
			'ssl' => 0,
			'inactivity' => 300,
		],
		'dev' => [
			'showerrors' => 1,
		],
	];
	Writer::write( $_config, 'config', 'etc/config/config.xml');
	chmod("./etc/config/config.xml", 0775);
	unlink( PATH_CACHE . '/__config.php.cache');
	echo 'OK' . PHP_EOL;
}

function app_db( $data ){
	echo 'Registrando base de datos...' . PHP_EOL;
	unlink( PATH_CACHE . '/__config.php.cache');
	$config = Reader::get();
	if( isset( $config[ 'bases' ][ $data[ 0 ] ] ) ) 
	$config[ 'bases' ][ $data[ 0 ] ][ 'type' ] = $data[ 1 ];
	$config[ 'bases' ][ $data[ 0 ] ][ 'host' ] = $data[ 2 ];
	$config[ 'bases' ][ $data[ 0 ] ][ 'user' ] = $data[ 3 ];
	$config[ 'bases' ][ $data[ 0 ] ][ 'dbname' ] = $data[ 4 ];
	$config[ 'bases' ][ $data[ 0 ] ][ 'password' ] = Crypt::encrypt( $data[ 5 ] );
	Writer::write( $config, 'config', 'etc/config/config.xml');
	chmod("./etc/config/config.xml", 0775);
	unlink( PATH_CACHE . '/__config.php.cache');
	echo 'OK' . PHP_EOL;
}

function db_restore( $data ) {
	$dbData = Reader::get( 'bases' );
	$dbData = $dbData[ $data[ 0 ] ];
	$dbData[ 'password' ] = trim( Crypt::decrypt( $dbData['password'] ) );
	$db = new DataManager( $dbData );

	$lines = file( $data[ 1 ] );
	$query = '';
	foreach ( $lines as $line ) {
		if ( substr( $line, 0, 2 ) == '--' || $line == '' )
		continue;
		$query .= $line;
		if ( substr( trim( $line ), -1, 1 ) == ';' ) {
			$db->query( $query );
			$query = '';
		}
	}
}

function user_new( $data ) {
	$config = Reader::get();
	var_dump($config, $data);
}

/**
 * Updates the principal DB with updates scripts
 * @return none
 */
function dbUpdate() {
	$data = Reader::get( 'bases' );
	$data = $data[ 'default' ];
	$data[ 'password' ] = trim( Crypt::decrypt( $data['password'] ) );
	$db = new DataManager( $data );
	echo 'Buscando actualizaciones disponibles...' . PHP_EOL;
	foreach ( glob( '*.upd.sql' ) as $update ) {
		echo '--' . $update . PHP_EOL;
		$lines = file( $update );
		$query = '';
		foreach ( $lines as $line ) {
			if ( substr( $line, 0, 2 ) == '--' || $line == '' )
			continue;
			$query .= $line;
			if ( substr( trim( $line ), -1, 1 ) == ';' ) {
				$db->query( $query );
				$query = '';
			}
		}
		rename( $update, './bkp/' . $update );
	}
	echo 'Actualizaciones aplicadas' . PHP_EOL;
}

/**
 * DUMP builder ( for a certain DB )
 * @param  string $key DB identifier
 * @return none
 */
function dbBackup( $key ) {
	if( trim( $key ) == '' )
		$key = 'default';
	$data = Reader::get( 'bases' );
	$data = $data[ $key ];
	$data[ 'password' ] = trim( Crypt::decrypt( $data['password'] ) );
	$db = new DataManager( $data );
	
	echo 'Respaldando información...' . PHP_EOL;

	if( $data['type'] == 'firebird' ) {
		$data[ 'dbname' ] = $key;
		$query = 'select rdb$relation_name AS Tables_in_' . $data[ 'dbname' ] .
			' from rdb$relations where rdb$view_blr is null and (rdb$system_flag is null or rdb$system_flag = 0);';
	} else {
		$query = 'SHOW TABLES';
	}
	$tables = $db->query( $query );

	$fileData = NULL;

	foreach($tables as $table) {
		if( $data['type'] == 'firebird' )
			$table = $table[ 'TABLES_IN_' . strtoupper( $data[ 'dbname' ] ) ];
		else
			$table = $table[ 'Tables_in_' . $data[ 'dbname' ] ];

		$tableData = $db->query('SELECT * FROM '.$table);
		
		if( $data['type'] != 'firebird' ) {
			$fileData.= "-- ----------------------------------------------\n" .
				"DROP TABLE IF EXISTS `" . $table . "`;";
			$create = $db->query( 'SHOW CREATE TABLE ' . $table );
			$fileData.= "\n\n" . str_replace('CREATE TABLE', 'CREATE TABLE IF NOT EXISTS ', $create[ 0 ][ 'Create Table' ] ) . ";\n\n";
		} else {
			$fileData.= "-- ----------------------------------------------\n";
		}

		if( count( $tableData ) > 0 ) {
			$fileData .= 'INSERT INTO `' . $table . '` (' .
				implode( ',', array_keys( $tableData[ 0 ] ) ) . ") VALUES \n";
			$dump = NULL;
			foreach( $tableData as $register ) {
				$dump[] = "('" . implode( "','", array_values( $register ) ) . "')";
			}
			$fileData .= implode(",\n", $dump) . ';';
			
		}
		$fileData.="\n\n";
	}

	$file = $key . '-backup-' . date("ymdGis") . '.sql';
	$handle = fopen('./bkp/' . $file ,'w+');
	fwrite($handle,$fileData);
	fclose($handle);
	echo 'Archivo ' . $file . ' creado' . PHP_EOL;
}

/**
 * Clean app cache
 * @return none
 */
function cacheClean($file = PATH_CACHE) {
	echo 'Limpiando cache...' . PHP_EOL;
	$files = glob(PATH_CACHE . '/*'); 
	foreach($files as $file){
		if (is_dir($file) and !in_array($file, array('..', '.')))  {
			cacheClean($file);
			rmdir($file);
		} else if(is_file($file) and ($file != __FILE__)) {
			unlink($file); 
		}
	}
	echo 'Cache limpia' . PHP_EOL;
}

/**
 * Terminate app sessions
 * @return none
 */
function sessionClean($file = PATH_SESSION) {
	echo 'Terminando sesiones...' . PHP_EOL;
	$files = glob(PATH_SESSION . '/*'); 
	foreach($files as $file){
		if (is_dir($file) and !in_array($file, array('..', '.')))  {
			sessionClean($file);
			rmdir($file);
		} else if(is_file($file) and ($file != __FILE__)) {
			unlink($file); 
		}
	}
	echo 'Sesiones cerradas' . PHP_EOL;
}